//go:build ignore

// gen_opencode_catalog.go regenerates opencode_catalog.go from models.dev, the
// catalogue OpenCode itself reads its providers from (it is what `/connect`
// lists). Run it from the module root on every OpenCode bump:
//
//	go run ./internal/daemon/gen_opencode_catalog.go
//
// or `go generate ./internal/daemon/`. It keeps every provider whose credential
// is a single API key in one environment variable — the only shape the Bailey
// setting can hand to a workspace — and drops the ones that need several
// values (Bedrock, Azure, Vertex, Cloudflare, Databricks, …); those are reached
// through a custom provider instead.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"time"
)

const source = "https://models.dev/api.json"
const output = "internal/daemon/opencode_catalog.go"

// popular is the short list the console shows first, each with a model hint
// that exists in the provider's catalogue (checked below).
var popular = []struct{ id, hint string }{
	{"anthropic", "claude-sonnet-4-5"},
	{"openai", "gpt-5"},
	{"google", "gemini-2.5-pro"},
	{"openrouter", "anthropic/claude-sonnet-4.5"},
	{"mistral", "mistral-large-latest"},
	{"groq", "llama-3.3-70b-versatile"},
	{"xai", "grok-4.7"},
	{"deepseek", "deepseek-v4-pro"},
	{"opencode", "gpt-5"},
}

// alternatives names the providers whose several env vars are alternative
// names for one key rather than several values; the first one is used.
var alternatives = map[string]bool{"google": true}

type provider struct {
	Name   string                     `json:"name"`
	Env    []string                   `json:"env"`
	Models map[string]json.RawMessage `json:"models"`
}

func main() {
	resp, err := http.Get(source)
	if err != nil {
		fail(err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil || resp.StatusCode != http.StatusOK {
		fail(fmt.Errorf("%s: %s %v", source, resp.Status, err))
	}
	var catalogue map[string]provider
	if err := json.Unmarshal(body, &catalogue); err != nil {
		fail(err)
	}

	hints := map[string]string{}
	for _, p := range popular {
		hints[p.id] = p.hint
	}
	ids := make([]string, 0, len(catalogue))
	for id := range catalogue {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	var out bytes.Buffer
	kept, skipped := 0, []string{}
	fmt.Fprintf(&out, "// Code generated by gen_opencode_catalog.go from %s on %s; DO NOT EDIT.\n\n", source, time.Now().UTC().Format("2006-01-02"))
	out.WriteString("package daemon\n\n")
	out.WriteString("// openCodeProviders is every provider in OpenCode's catalogue that takes a\n")
	out.WriteString("// single API key in one environment variable, as the console offers them;\n")
	out.WriteString("// the popular ones carry a checked model hint, the rest a model the provider\n")
	out.WriteString("// serves. Regenerate on an OpenCode bump (see gen_opencode_catalog.go).\n")
	out.WriteString("var openCodeProviders = []openCodeProvider{\n")
	for _, id := range ids {
		p := catalogue[id]
		if len(p.Env) == 0 || (len(p.Env) > 1 && !alternatives[id]) || p.Name == "" {
			skipped = append(skipped, id)
			continue
		}
		models := make([]string, 0, len(p.Models))
		for m := range p.Models {
			models = append(models, m)
		}
		sort.Strings(models)
		hint, isPopular := hints[id]
		if isPopular {
			if _, ok := p.Models[hint]; !ok {
				fmt.Fprintf(os.Stderr, "warning: %s: hint %q is not in the catalogue any more\n", id, hint)
				hint = ""
			}
		}
		if hint == "" && len(models) > 0 {
			hint = models[0]
		}
		fmt.Fprintf(&out, "\t{ID: %q, Name: %q, Env: %q, ModelHint: %q", id, p.Name, p.Env[0], hint)
		if isPopular {
			out.WriteString(", Popular: true")
		}
		out.WriteString("},\n")
		kept++
	}
	out.WriteString("}\n")
	fmt.Fprintf(&out, "\n// openCodeCatalogueSize is how many providers models.dev listed when the table\n// was generated; %d of them are above, the rest need more than one key.\nconst openCodeCatalogueSize = %d\n", kept, len(catalogue))

	src, err := format.Source(out.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(output, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("%s: %d providers kept, %d skipped (%v)\n", output, kept, len(skipped), skipped)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen_opencode_catalog:", err)
	os.Exit(1)
}
