package daemon

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/bitswan-space/bitswan-workspaces/internal/services"
)

// A server-wide default model provider for OpenCode.
//
// OpenCode, the second coding agent in every workspace's Coding Agent tab,
// takes provider credentials from the environment of its `opencode serve`
// process (ANTHROPIC_API_KEY makes the anthropic provider appear, and so on)
// and its default model from the `model` key of its config. Without either,
// each person connects a provider in OpenCode's own UI, and until they do
// OpenCode answers through its built-in hosted provider.
//
// This setting hands every workspace one key instead:
//
//	console  POST /bailey/api/admin/opencode-provider
//	  → server_settings[opencode_default_provider]           (bailey.db; the key never leaves the server)
//	  → <ws>/coding-agent-home/.bitswan/opencode-provider.env (every workspace with the agent enabled;
//	                                                            /home/agent/.bitswan/… inside the container)
//	  → bitswan-opencode-server `start` sources it and starts `opencode serve` with the
//	    provider's env var set and a generated config carrying `model` — and, when
//	    restricted, a policy that hides every other provider.
//
// A file in the agent's home rather than compose environment: nothing to
// regenerate and no container to restart when the key changes, the key never
// lands in the world-readable compose file, and every server started after a
// change picks it up (a running one on its next start). The file is written on
// save, when the agent is enabled for a workspace, and on every reconcile tick;
// it is removed the same way when the setting is disabled or cleared.
//
// Exposure, and the console says so: everything in the agent container runs
// as the agent user, so every coding-agent run in every workspace can read the
// key. That is what "every workspace uses this key" means.

// openCodeProvider is one entry of the provider table the console offers:
// OpenCode's own catalogue (models.dev), reduced to the providers whose
// credential is one API key in one environment variable. The table lives in
// opencode_catalog.go, generated by gen_opencode_catalog.go; regenerate it on
// an OpenCode bump (docs/opencode-integration.md, upgrade section).
type openCodeProvider struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Env  string `json:"env"`
	// ModelHint is a model id the provider serves today, as the console's
	// placeholder; the admin types the one they want.
	ModelHint string `json:"model_hint,omitempty"`
	// Popular marks the short list the console shows before the rest.
	Popular bool `json:"popular,omitempty"`
}

//go:generate go run gen_opencode_catalog.go

func openCodeProviderByID(id string) (openCodeProvider, bool) {
	for _, p := range openCodeProviders {
		if p.ID == id {
			return p, true
		}
	}
	return openCodeProvider{}, false
}

// openCodePackage is one of OpenCode's runtime provider packages a custom
// endpoint can be spoken to through, by the name after @opencode/ai/providers/.
// The list is what 2.0.16 ships; re-check it on a bump.
type openCodePackage struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

var openCodePackages = []openCodePackage{
	{ID: "openai-compatible", Name: "OpenAI-compatible (chat completions)"},
	{ID: "anthropic-compatible", Name: "Anthropic-compatible (messages)"},
	{ID: "openai", Name: "OpenAI"},
	{ID: "anthropic", Name: "Anthropic"},
	{ID: "google", Name: "Google Gemini"},
}

func openCodePackageByID(id string) (openCodePackage, bool) {
	for _, p := range openCodePackages {
		if p.ID == id {
			return p, true
		}
	}
	return openCodePackage{}, false
}

// openCodeCustomModel is one model a custom provider serves. A custom provider
// has no catalogue, so the admin names its models (unless it inherits them).
type openCodeCustomModel struct {
	ID   string `json:"id"`
	Name string `json:"name,omitempty"`
}

// openCodeCustomProvider describes a provider that is not in OpenCode's
// catalogue: an endpoint of the admin's own — a company gateway, a self-hosted
// model server — reached through one of OpenCode's runtime packages. Its id is
// the setting's Provider, its endpoint the setting's BaseURL, and its key
// travels under openCodeCustomKeyEnv.
type openCodeCustomProvider struct {
	Name      string                `json:"name"`
	Package   string                `json:"package"`
	Canonical string                `json:"canonical,omitempty"`
	Models    []openCodeCustomModel `json:"models,omitempty"`
}

// openCodeCustomKeyEnv is the env var a custom provider reads its key from;
// the launcher names it in the generated provider entry.
const openCodeCustomKeyEnv = "BITSWAN_OPENCODE_API_KEY"

// openCodeProviderConfig is the stored setting: one JSON blob under
// settingOpenCodeProvider, the way the SSO setting is kept. The key stays
// inside it; nothing but the env file ever reads it back out.
//
// Provider is a catalogue id, or the custom provider's own id when Custom is
// set. BaseURL is optional for a catalogue provider (its endpoint override,
// for a proxy or gateway) and required for a custom one.
type openCodeProviderConfig struct {
	Enabled   bool                    `json:"enabled"`
	Provider  string                  `json:"provider"`
	Model     string                  `json:"model"`
	APIKey    string                  `json:"api_key"`
	Restrict  bool                    `json:"restrict"`
	BaseURL   string                  `json:"base_url,omitempty"`
	Custom    *openCodeCustomProvider `json:"custom,omitempty"`
	UpdatedAt string                  `json:"updated_at"`
	UpdatedBy string                  `json:"updated_by"`
}

// keyEnv is the env var the provider reads its key from.
func (c openCodeProviderConfig) keyEnv() string {
	if c.Custom != nil {
		return openCodeCustomKeyEnv
	}
	if p, ok := openCodeProviderByID(c.Provider); ok {
		return p.Env
	}
	return ""
}

func getOpenCodeProvider() (openCodeProviderConfig, error) {
	raw, err := dbGetSetting(settingOpenCodeProvider)
	if err != nil {
		return openCodeProviderConfig{}, err
	}
	if strings.TrimSpace(raw) == "" {
		return openCodeProviderConfig{}, nil
	}
	var c openCodeProviderConfig
	if err := json.Unmarshal([]byte(raw), &c); err != nil {
		return openCodeProviderConfig{}, fmt.Errorf("stored OpenCode provider setting is corrupt: %w", err)
	}
	return c, nil
}

func setOpenCodeProvider(c openCodeProviderConfig, by string) error {
	c.UpdatedAt = time.Now().UTC().Format(time.RFC3339)
	c.UpdatedBy = by
	b, err := json.Marshal(c)
	if err != nil {
		return err
	}
	return dbSetSetting(settingOpenCodeProvider, string(b), by)
}

// hasControlChars reports a byte that no provider id, model id or API key
// contains — and that a line-oriented env file must never be handed.
func hasControlChars(s string) bool {
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			return true
		}
	}
	return false
}

// customProviderIDRe is the shape of a custom provider id: it becomes the
// prefix of every model reference (`<id>/<model>`) and a policy resource.
var customProviderIDRe = regexp.MustCompile(`^[a-z0-9][a-z0-9_-]{0,63}$`)

func validModelID(id string) bool {
	return id != "" && !strings.Contains(id, "#") && !strings.ContainsAny(id, " \t") && !hasControlChars(id)
}

// validateBaseURL accepts an absolute http(s) URL with a host and nothing a
// shell line or a JSON string could trip over.
func validateBaseURL(raw string) error {
	if hasControlChars(raw) || strings.ContainsAny(raw, " \t\"'") {
		return fmt.Errorf("the endpoint URL contains characters a URL cannot")
	}
	u, err := url.Parse(raw)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return fmt.Errorf("the endpoint must be an http(s) URL, e.g. https://llm.example.com/v1")
	}
	return nil
}

// validateOpenCodeProvider checks a setting about to be stored. An enabled
// setting needs all of provider, model and key (and, for a custom provider,
// an endpoint and models to offer); a disabled one may be partial — it keeps
// whatever was there for a one-click re-enable — but what it carries must
// still be well-formed.
func validateOpenCodeProvider(c openCodeProviderConfig) error {
	switch {
	case c.Custom != nil:
		if !customProviderIDRe.MatchString(c.Provider) {
			return fmt.Errorf("a custom provider id is lowercase letters, digits, '-' and '_' (e.g. acme)")
		}
		if _, ok := openCodeProviderByID(c.Provider); ok {
			return fmt.Errorf("%q is a provider in OpenCode's catalogue — choose it from the list, or give the custom provider another id", c.Provider)
		}
		if hasControlChars(c.Custom.Name) {
			return fmt.Errorf("the display name contains characters it cannot")
		}
		if _, ok := openCodePackageByID(c.Custom.Package); !ok {
			return fmt.Errorf("choose which API the endpoint speaks")
		}
		if c.Custom.Canonical != "" {
			if _, ok := openCodeProviderByID(c.Custom.Canonical); !ok {
				return fmt.Errorf("models can only be inherited from a provider in the catalogue")
			}
		}
		listed := false
		for _, m := range c.Custom.Models {
			if !validModelID(m.ID) || hasControlChars(m.Name) {
				return fmt.Errorf("a listed model needs an id without spaces or '#'")
			}
			listed = listed || m.ID == c.Model
		}
		if c.Enabled {
			if c.BaseURL == "" {
				return fmt.Errorf("a custom provider needs an endpoint URL")
			}
			if len(c.Custom.Models) == 0 && c.Custom.Canonical == "" {
				return fmt.Errorf("list at least one model, or inherit the models of a catalogue provider")
			}
			if len(c.Custom.Models) > 0 && c.Custom.Canonical == "" && c.Model != "" && !listed {
				return fmt.Errorf("the default model must be one of the listed models")
			}
		}
	case c.Provider != "" || c.Enabled:
		if _, ok := openCodeProviderByID(c.Provider); !ok {
			return fmt.Errorf("choose a provider from the list")
		}
	}
	if c.BaseURL != "" {
		if err := validateBaseURL(c.BaseURL); err != nil {
			return err
		}
	}
	if c.Enabled && c.Model == "" {
		return fmt.Errorf("a model is required — it is the one OpenCode uses unless a person picks another")
	}
	if c.Model != "" && !validModelID(c.Model) {
		return fmt.Errorf("the model id may not contain spaces or '#'")
	}
	if c.Enabled && c.APIKey == "" {
		return fmt.Errorf("an API key is required")
	}
	if hasControlChars(c.APIKey) {
		return fmt.Errorf("the API key contains characters that cannot be part of a key")
	}
	return nil
}

// --- the file in each workspace's agent home ---------------------------------

const openCodeProviderEnvFile = "opencode-provider.env"

// openCodeProviderEnvPath is where a workspace's agent finds the file. The
// coding-agent compose mounts coding-agent-home at /home/agent, so inside the
// container this is /home/agent/.bitswan/opencode-provider.env — the path
// bitswan-opencode-server reads.
func openCodeProviderEnvPath(workspacePath string) string {
	return filepath.Join(workspacePath, "coding-agent-home", ".bitswan", openCodeProviderEnvFile)
}

// shellSingleQuote quotes s for a POSIX shell. Inside single quotes nothing
// expands, and an embedded quote becomes '\”. The file is sourced by bash,
// where a double-quoted $, backtick or backslash would expand or run — so it
// is never strconv.Quote.
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// renderOpenCodeProviderEnv is the file for c, or "" when there should be no
// file at all (disabled or incomplete). One NAME='value' per line: the
// BITSWAN_OPENCODE_* lines tell the launcher what to generate — the provider
// and model, an endpoint override, a custom provider's description — and the
// last line is the env var the provider reads its key from, the only place
// the key ever appears.
func renderOpenCodeProviderEnv(c openCodeProviderConfig) string {
	if !c.Enabled || validateOpenCodeProvider(c) != nil || c.APIKey == "" {
		return ""
	}
	env := c.keyEnv()
	if env == "" {
		return ""
	}
	var b strings.Builder
	b.WriteString("# Written by the Bailey automation server from the server-wide OpenCode\n")
	b.WriteString("# provider setting; overwritten on every change. bitswan-opencode-server\n")
	b.WriteString("# sources this file when it starts a server.\n")
	line := func(name, value string) { fmt.Fprintf(&b, "%s=%s\n", name, shellSingleQuote(value)) }
	line("BITSWAN_OPENCODE_PROVIDER", c.Provider)
	line("BITSWAN_OPENCODE_PROVIDER_ENV", env)
	line("BITSWAN_OPENCODE_MODEL", c.Model)
	line("BITSWAN_OPENCODE_RESTRICT", strconv.FormatBool(c.Restrict))
	if c.BaseURL != "" {
		line("BITSWAN_OPENCODE_BASE_URL", c.BaseURL)
	}
	if c.Custom != nil {
		line("BITSWAN_OPENCODE_CUSTOM", "true")
		line("BITSWAN_OPENCODE_CUSTOM_NAME", c.Custom.Name)
		line("BITSWAN_OPENCODE_CUSTOM_PACKAGE", c.Custom.Package)
		if c.Custom.Canonical != "" {
			line("BITSWAN_OPENCODE_CUSTOM_CANONICAL", c.Custom.Canonical)
		}
		if len(c.Custom.Models) > 0 {
			models, _ := json.Marshal(c.Custom.Models)
			line("BITSWAN_OPENCODE_CUSTOM_MODELS", string(models))
		}
	}
	line(env, c.APIKey)
	return b.String()
}

// The agent user inside the coding-agent image; services.CodingAgentService
// hands it the agent home the same way when the agent is enabled.
const agentUID, agentGID = 1000, 1000

// chownToAgent gives the agent user a path the daemon wrote into the agent's
// home. Mirrors CodingAgentService.Enable: plain chown as root, sudo otherwise.
// A variable so tests, which need no root, can watch it instead.
var chownToAgent = func(path string) error {
	if os.Geteuid() == 0 {
		return os.Chown(path, agentUID, agentGID)
	}
	out, err := exec.Command("sudo", "chown", strconv.Itoa(agentUID)+":"+strconv.Itoa(agentGID), path).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// openCodeProviderSyncMu serialises syncs: the reconcile tick and a console
// save can run at once, and each must see the setting as it is when it runs,
// or the tick could put a just-replaced key back until the next tick.
var openCodeProviderSyncMu sync.Mutex

// syncOpenCodeProviderFiles brings every workspace's copy of the provider
// file in line with the setting. Per-workspace failures are logged and skipped:
// one broken workspace must not keep the others from getting the key.
func syncOpenCodeProviderFiles() {
	openCodeProviderSyncMu.Lock()
	defer openCodeProviderSyncMu.Unlock()
	cfg, err := getOpenCodeProvider()
	if err != nil {
		fmt.Printf("opencode provider: could not read the setting: %v\n", err)
		return
	}
	content := renderOpenCodeProviderEnv(cfg)
	names, err := listWorkspaceNames()
	if err != nil {
		fmt.Printf("opencode provider: could not list workspaces: %v\n", err)
		return
	}
	for _, ws := range names {
		if err := syncOpenCodeProviderFileWith(ws, content); err != nil {
			fmt.Printf("opencode provider: workspace '%s': %v\n", ws, err)
		}
	}
}

// syncOpenCodeProviderFileForWorkspace is the one-workspace form, for the
// moment the agent is enabled in a workspace.
func syncOpenCodeProviderFileForWorkspace(ws string) error {
	openCodeProviderSyncMu.Lock()
	defer openCodeProviderSyncMu.Unlock()
	cfg, err := getOpenCodeProvider()
	if err != nil {
		return err
	}
	return syncOpenCodeProviderFileWith(ws, renderOpenCodeProviderEnv(cfg))
}

func syncOpenCodeProviderFileWith(ws, content string) error {
	// A recovery is replacing the workspace directory, and a trashed workspace
	// has no running agent; neither is touched (listWorkspaceNames lists both).
	if workspaceUnderRecovery(ws) || IsWorkspaceTrashed(ws) {
		return nil
	}
	svc, err := services.NewCodingAgentService(ws)
	if err != nil || !svc.IsEnabled() {
		return nil
	}
	return writeOpenCodeProviderFile(svc.WorkspacePath, content)
}

// writeOpenCodeProviderFile puts content at the workspace's provider path, or
// removes the file when content is empty. A workspace whose agent home does
// not exist is skipped: Enable creates the home, this never does.
//
// It writes only on a change, through a temp file in the same directory, and
// hands the directory and the file to the agent user before the rename. The
// daemon runs as root and the container's own chown of /home/agent runs only
// when the container starts, so a root-owned 0600 file dropped into a running
// container would be unreadable by the agent — and the next server would
// start without the provider, silently.
func writeOpenCodeProviderFile(workspacePath, content string) error {
	home := filepath.Join(workspacePath, "coding-agent-home")
	if st, err := os.Stat(home); err != nil || !st.IsDir() {
		return nil
	}
	path := openCodeProviderEnvPath(workspacePath)
	if content == "" {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove %s: %w", path, err)
		}
		return nil
	}
	if cur, err := os.ReadFile(path); err == nil && string(cur) == content {
		return nil
	}
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	if err := chownToAgent(dir); err != nil {
		return fmt.Errorf("chown %s: %w", dir, err)
	}
	tmp, err := os.CreateTemp(dir, "."+openCodeProviderEnvFile+".*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	fail := func(err error) error {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return err
	}
	if err := tmp.Chmod(0o600); err != nil {
		return fail(err)
	}
	if _, err := tmp.WriteString(content); err != nil {
		return fail(err)
	}
	if err := tmp.Close(); err != nil {
		return fail(err)
	}
	if err := chownToAgent(tmpPath); err != nil {
		return fail(fmt.Errorf("chown %s: %w", tmpPath, err))
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fail(fmt.Errorf("rename into place: %w", err))
	}
	return nil
}

// --- the admin API --------------------------------------------------------------

// openCodeProviderDTO is what the console sees. The key itself is never in it;
// key_set and the last few characters are enough to tell which key is stored.
type openCodeProviderDTO struct {
	Enabled   bool                    `json:"enabled"`
	Provider  string                  `json:"provider"`
	Model     string                  `json:"model"`
	Restrict  bool                    `json:"restrict"`
	BaseURL   string                  `json:"base_url,omitempty"`
	Custom    *openCodeCustomProvider `json:"custom,omitempty"`
	KeySet    bool                    `json:"key_set"`
	KeyHint   string                  `json:"key_hint,omitempty"`
	UpdatedAt string                  `json:"updated_at,omitempty"`
	UpdatedBy string                  `json:"updated_by,omitempty"`
	Providers []openCodeProvider      `json:"providers"`
	Packages  []openCodePackage       `json:"packages"`
}

func openCodeProviderDTOFrom(c openCodeProviderConfig) openCodeProviderDTO {
	d := openCodeProviderDTO{
		Enabled:   c.Enabled,
		Provider:  c.Provider,
		Model:     c.Model,
		Restrict:  c.Restrict,
		BaseURL:   c.BaseURL,
		Custom:    c.Custom,
		KeySet:    c.APIKey != "",
		UpdatedAt: c.UpdatedAt,
		UpdatedBy: c.UpdatedBy,
		Providers: openCodeProviders,
		Packages:  openCodePackages,
	}
	if n := len(c.APIKey); n >= 12 {
		d.KeyHint = c.APIKey[n-4:]
	}
	return d
}

func writeOpenCodeProviderDTO(w http.ResponseWriter) {
	c, err := getOpenCodeProvider()
	if err != nil {
		writeJSONError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	writeJSON(w, openCodeProviderDTOFrom(c))
}

// GET /bailey/api/admin/opencode-provider
func handleOpenCodeProviderGet(w http.ResponseWriter, r *http.Request) {
	writeOpenCodeProviderDTO(w)
}

// openCodeProviderRequest is the POST body. A blank api_key keeps the stored
// key (the console never has it to send back); enabled:false keeps everything
// and removes the files, so one click brings it back; clear:true forgets the
// setting, key included. There are no DELETE routes in the dispatcher, so
// clearing is a POST like the default-images setting.
type openCodeProviderRequest struct {
	Enabled  bool                    `json:"enabled"`
	Provider string                  `json:"provider"`
	Model    string                  `json:"model"`
	APIKey   string                  `json:"api_key"`
	Restrict bool                    `json:"restrict"`
	BaseURL  string                  `json:"base_url"`
	Custom   *openCodeCustomProvider `json:"custom"`
	Clear    bool                    `json:"clear"`
}

// tidyCustomProvider trims a submitted custom provider, drops empty model rows
// and gives it a display name when none was typed.
func tidyCustomProvider(id string, in *openCodeCustomProvider) *openCodeCustomProvider {
	if in == nil {
		return nil
	}
	out := &openCodeCustomProvider{
		Name:      strings.TrimSpace(in.Name),
		Package:   strings.TrimSpace(in.Package),
		Canonical: strings.TrimSpace(in.Canonical),
	}
	if out.Name == "" {
		out.Name = id
	}
	for _, m := range in.Models {
		m.ID, m.Name = strings.TrimSpace(m.ID), strings.TrimSpace(m.Name)
		if m.ID != "" || m.Name != "" {
			out.Models = append(out.Models, m)
		}
	}
	return out
}

// POST /bailey/api/admin/opencode-provider
func handleOpenCodeProviderSet(w http.ResponseWriter, r *http.Request, by string) {
	var req openCodeProviderRequest
	if err := json.NewDecoder(io.LimitReader(r.Body, 64<<10)).Decode(&req); err != nil {
		writeJSONError(w, "bad request", http.StatusBadRequest)
		return
	}
	if req.Clear {
		if err := dbDeleteSetting(settingOpenCodeProvider); err != nil {
			writeJSONError(w, err.Error(), http.StatusInternalServerError)
			return
		}
		syncOpenCodeProviderFiles()
		_ = recordEvent(by, "opencode.provider.clear", "")
		writeOpenCodeProviderDTO(w)
		return
	}

	existing, err := getOpenCodeProvider()
	if err != nil {
		writeJSONError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	c := openCodeProviderConfig{
		Enabled:  req.Enabled,
		Provider: strings.TrimSpace(req.Provider),
		Model:    strings.TrimSpace(req.Model),
		APIKey:   strings.TrimSpace(req.APIKey),
		Restrict: req.Restrict,
		BaseURL:  strings.TrimSpace(req.BaseURL),
	}
	c.Custom = tidyCustomProvider(c.Provider, req.Custom)
	if c.APIKey == "" {
		c.APIKey = existing.APIKey
	}
	if err := validateOpenCodeProvider(c); err != nil {
		writeJSONCodeError(w, err.Error(), "invalid_config", http.StatusBadRequest)
		return
	}
	if err := setOpenCodeProvider(c, by); err != nil {
		writeJSONError(w, err.Error(), http.StatusInternalServerError)
		return
	}
	syncOpenCodeProviderFiles()
	if c.Enabled {
		_ = recordEvent(by, "opencode.provider.configure", c.Provider+"/"+c.Model)
	} else {
		_ = recordEvent(by, "opencode.provider.disable", c.Provider)
	}
	writeOpenCodeProviderDTO(w)
}
